Add files via upload

diff --git a/Plus b/Plus
--- a/Plus
+++ b/Plus
@@ -52,6 +52,17 @@ function verif_key() {
         exit 1
     }
 }
+function verif_key2() {
+    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
+    chmod +x $_Ink/listARM >/dev/null 2>&1
+    [[ ! -e "$_Ink/listARM" ]] && {
+        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
+        rm -rf $HOME/Plus >/dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
+}
 
 otimize_python() {
     # INSTALA PYTHON AO PYTHON2
@@ -75,40 +86,67 @@ otimize_python() {
     #SETAR PYTHON3
     update-alternatives --set python3 /usr/bin/python3.6
 }
-figlet "RAFAEL SSH" | lolcat
-echo "INSTALAÇÃO EM ANDAMENTO....."
+figlet "SSH-PRO" | lolcat
+echo "SCRIPT RAFAEL SSH !!"
+echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
+echo ""
+echo ""
+echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
+echo ""
+echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"
+echo -e "\033[1;31m \033[1;33m\033[0m"
+echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"
+echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"
+echo -e "\033[1;31m \033[1;33m\033[0m"
+echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
 #-----------------------------------------------------------------------------------------------------------------
-echo -e "\n\033[1;37mINICIANDO. \033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficia/main/Install/list >/dev/null 2>&1
+echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;36mDIGITE ENTER PRA CONTINUAR (n) SAIR:\033[1;37m"; read x
+[[ $x = @(n|N) ]] && exit
+echo -e "\033[1;36m SISTEMA DA VPS ?: \033[1;37m"
+echo -e "[1] - x86_64"
+echo -e "[2] - aarch64(ARM)"
+echo -ne "\033[1;36mOpção: \033[1;37m"
+read resposta
+if [[ "$resposta" = '1' ]]; then
+    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
+    service ssh restart >/dev/null 2>&1
+    mkdir /etc/rec >/dev/null 2>&1
+    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
+    rm $_Ink/list >/dev/null 2>&1
+    wget -P $_Ink https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/install/list >/dev/null 2>&1
     verif_key
     sleep 3s
     echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
     rm versao* >/dev/null 2>&1
-    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficia/main/Install/versao >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/install/versao >/dev/null 2>&1
     rm v2raymanager >/dev/null 2>&1
-    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficia/SSHPLUS/main/Modulos/v2raymanager >/dev/null 2>&1
-    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficia/main/Modulos/botteste.sh >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/botteste.sh >/dev/null 2>&1
     chmod 777 v2raymanager >/dev/null 2>&1
     chmod 777 botteste.sh >/dev/null 2>&1
     mkdir $HOME/BOT >/dev/null 2>&1
     cd $HOME/BOT
-    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficia/main/Modulos/ShellBot.sh >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/ShellBot.sh >/dev/null 2>&1
     chmod 777 ShellBot.sh >/dev/null 2>&1
     cd >/dev/null 2>&1
     chmod 777 licence >/dev/null 2>&1
     mkdir /etc/rec >/dev/null 2>&1
     cd /etc/rec
-    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficia/main/Modulos/licence >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/licence >/dev/null 2>&1
     chmod 777 licence >/dev/null 2>&1
     cd >/dev/null 2>&1
-    wget $HOME -O TBotPlus.zip https://www.dropbox.com/s/k20n9u3wwgb10vn/TBotPlus.zip?dl=0
     #-----------------------------------------------------------------------------------------------------------------
     echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
     sleep 1s
     echo ""
     [[ -f "$HOME/usuarios.db" ]] && {
         clear
-        figlet "RAFAEL SSH" | lolcat
-        echo "SCRIPT RAFAEL SSH PREMIUM" 
+        figlet "SSH-PRO" | lolcat
+        echo "SCRIPT RAFAEL SSH !!" 
         echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
         echo -e "\033[1;33mOPA DETECTAMOS..."
         echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
@@ -152,9 +190,9 @@ echo -e "\n\033[1;37mINICIANDO. \033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget 
     fun_bar 'fun_attlist'
     clear
     echo ""
-    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;37mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
     echo ""
-    echo -e "\033[1;37mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
+    echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
     echo ""
     inst_pct() {
         _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
@@ -171,45 +209,180 @@ echo -e "\n\033[1;37mINICIANDO. \033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget 
     ufw allow 8080/tcp
     clear
     echo ""
-    unzip TBotPlus.zip
-    clear
     echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
     echo ""
-    echo -e "      \033[1;37mOTIMIZANDO PYTHON \033[0m"
+    echo -e "      \033[1;33mOTIMIZANDO PYTHON \033[0m"
     echo ""
     fun_bar 'otimize_python'
     clear
     echo ""
     echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
     echo ""
-    echo -e "      \033[1;37mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
+    echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
     echo ""
     fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
     clear
     echo ""
     cd $HOME
-    cd TBotPlus; chmod +x TerminusBot.sh && ./TerminusBot.sh && wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
-    clear
-    echo -e "        \033[1;33m • \033[1;37mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
+    echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
     echo ""
     cd $HOME
     echo "clear" >>/root/.bashrc
     echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
     echo 'TIME=$(date +"%T")' >>/root/.bashrc
-    echo 'figlet -k RAFAEL SSH | lolcat' >>/root/.bashrc
+    echo 'figlet -k SSH-PRO | lolcat' >>/root/.bashrc
     echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
     echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
     echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
     echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
     echo 'echo -e "@RAFAELSSH"' >>.bashrc
-    echo -e "\033[1;37mUSE O COMANDO COMANDO PARA O BOT WHATSAPP FUNCIONA 👉 \033[1;36m nvm install 16 👈\033[0m"
     echo 'echo -e "\033[1;31m DIGITE ( menu ) PARA ENTRAR\033[0m."' >>/root/.bashrc
     echo 'echo -e ""' >>/root/.bashrc
     date=$(date '+%Y-%m-%d <> %H:%M:%S')
     echo -e "\033[1;37m $system                          $date"
-    figlet "RAFAEL SSH" | lolcat
+    figlet "SSH-PRO" | lolcat
     echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                INSTALACAO CONCLUIDA               \033[1;33m \033[0m\033[01;31m║"
-    echo -e "\033[01;31m║\033[1;37mPARA INICIAR DIGITE: \033[1;36mmenu\033[0m"
+    echo -e "\033[01;31m║\033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
+    echo -e "\033[01;31m║\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@Rafaelssh\033[0m"
     rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
-    
+elif [[ "$resposta" = '2' ]]; then
+    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
+    service ssh restart >/dev/null 2>&1
+    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
+    rm $_Ink/listARM >/dev/null 2>&1
+    wget -P $_Ink https://www.dropbox.com/s/cs5poyigwm97dyd/listARM >/dev/null 2>&1
+    verif_key2
+    sleep 3s
+    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
+    rm versao* >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/install/versao >/dev/null 2>&1
+    rm v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/botteste.sh >/dev/null 2>&1
+    chmod 777 v2raymanager >/dev/null 2>&1
+    chmod 777 botteste.sh >/dev/null 2>&1
+    mkdir $HOME/BOT >/dev/null 2>&1
+    cd $HOME/BOT
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/ShellBot.sh >/dev/null 2>&1
+    chmod 777 ShellBot.sh >/dev/null 2>&1
+    cd >/dev/null 2>&1
+    chmod 777 licence >/dev/null 2>&1
+    mkdir /etc/rec >/dev/null 2>&1
+    cd /etc/rec
+    wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/F2/Modulos/licence >/dev/null 2>&1
+    chmod 777 licence >/dev/null 2>&1
+    cd >/dev/null 2>&1
+    #-----------------------------------------------------------------------------------------------------------------
+    echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
+    sleep 1s
+    echo ""
+    [[ -f "$HOME/usuarios.db" ]] && {
+        clear
+        figlet "SSH-PRO" | lolcat
+        echo "SCRIPT DO RAFAEL SSH !!" 
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
+        echo -e "\033[1;33mOPA DETECTAMOS..."
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
+        echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
+        echo ""
+        echo -e "\033[1;33m🗣️ LOGIN"
+        echo -e "\033[1;33m🔑 SENHAS"
+        echo -e "\033[1;33m📲 LIMITE"
+        echo -e "\033[1;33m⌛ DIAS"
+        echo -e ""
+        echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
+        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMANTER DADOS ATUAL\033[0m"
+        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCRIAR UMA NOVA BASE DE DADOS\033[0m"
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━\033[0m"
+        echo ""
+        tput setaf 2
+        tput bold
+        read -p "Opção ?: " -e -i 1 optiondb
+        tput sgr0
+    } || {
+        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    }
+    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    clear
+    tput setaf 7
+    tput setab 4
+    tput bold
+    printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO"
+    tput sgr0
+    echo ""
+    echo ""
+    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo ""
+    echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
+    echo ""
+    fun_attlist() {
+        apt-get update -y
+        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
+        echo "crz: $(date)" >/usr/share/.plus/.plus
+    }
+    fun_bar 'fun_attlist'
+    clear
+    echo ""
+    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo ""
+    echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
+    echo ""
+    inst_pct() {
+        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
+        for _prog in ${_pacotes[@]}; do
+            apt install $_prog -y
+        done
+        pip install speedtest-cli
+    }
+    fun_bar 'inst_pct'
+    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
+    ufw allow 80/tcp
+    ufw allow 3128/tcp
+    ufw allow 8799/tcp
+    ufw allow 8080/tcp
+    clear
+    echo ""
+    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo ""
+    echo -e "      \033[1;33mOTIMIZANDO PYTHON \033[0m"
+    echo ""
+    fun_bar 'otimize_python'
+    clear
+    echo ""
+    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+    echo ""
+    echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
+    echo ""
+    fun_bar "$_Ink/listARM $_lnk $_Ink $_1nk $key"
+    clear
+    echo ""
+    cd $HOME
+    echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
+    echo ""
+    cd $HOME
+    echo "clear" >>/root/.bashrc
+    echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
+    echo 'TIME=$(date +"%T")' >>/root/.bashrc
+    echo 'figlet -k SSH-PRO | lolcat' >>/root/.bashrc
+    echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
+    echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
+    echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
+    echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
+    echo 'echo -e "@Rafaelssh"' >>.bashrc
+    echo 'echo -e "\033[1;31m DIGITE ( menu ) PARA ENTRAR\033[0m."' >>/root/.bashrc
+    echo 'echo -e ""' >>/root/.bashrc
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "SSH-PRO" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                INSTALACAO CONCLUIDA               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
+    echo -e "\033[01;31m║\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@Rafaelssh\033[0m"
+    rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
 
+else
+
+    echo ""
+    echo -e "\033[1;31mOpcao invalida !\033[0m"
+    sleep 1
+    exit
+fi
