Add files via upload

diff --git a/F2/Modulos/conexao b/F2/Modulos/conexao
--- a/F2/Modulos/conexao
+++ b/F2/Modulos/conexao
@@ -1501,16 +1501,16 @@ exit 0' >$RCLOCAL
 		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
 		read resposta
 		if [[ "$resposta" = '1' ]]; then
-			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+			if ps x | grep -w antcrashvpn2.sh | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				echo -e "\E[41;1;37m             PROXY SOCKS              \E[0m"
 				echo ""
 				fun_socksoff() {
 					for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
-						screen -r -S "$pidproxy" -X quit
+						screen -X -S "$pidproxy" kill
 					done
-					[[ $(grep -wc "proxy.py" /etc/autostart) != '0' ]] && {
-						sed -i '/proxy.py/d' /etc/autostart
+					[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) != '0' ]] && {
+						sed -i '/antcrashvpn2.sh/d' /etc/autostart
 					}
 					sleep 1
 					screen -wipe >/dev/null
@@ -1538,12 +1538,12 @@ exit 0' >$RCLOCAL
 				verif_ptrs $porta
 				fun_inisocks() {
 					sleep 1
-					screen -dmS proxy python /etc/SSHPlus/proxy.py $porta
-					[[ $(grep -wc "proxy.py" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
+					screen -dmS proxy antcrashvpn2.sh "$porta"
+					[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy antcrashvpn2.sh $porta" >>/etc/autostart
 					} || {
-						sed -i '/proxy.py/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
+						sed -i '/antcrashvpn2.sh/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy antcrashvpn2.sh $porta" >>/etc/autostart
 					}
 				}
 				echo ""
@@ -1555,34 +1555,85 @@ exit 0' >$RCLOCAL
 				sleep 3
 				fun_socks
 			fi
-
-
-
-        elif [[ "$resposta" = '2' ]]; then
-			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+		elif [[ "$resposta" = '2' ]]; then
+			if ps x | grep -w antcrashvpn3.sh | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
-				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
+				echo -e "\E[41;1;37m            SOCKS OPENVPN + ANTCRASH             \E[0m"
 				echo ""
-				fun_wssocksoff() {
-					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+				fun_socksopenoff() {
+					for pidproxy in $(screen -list | grep -w "proxy2" | awk {'print $1'}); do
 						screen -r -S "$pidproxy" -X quit
 					done
-					[[ $(grep -wc "wsproxy.py" /etc/autostart) != '0' ]] && {
-						sed -i '/wsproxy.py/d' /etc/autostart
+					[[ $(grep -wc "antcrashvpn3.sh" /etc/autostart) != '0' ]] && {
+						sed -i '/antcrashvpn3.sh/d' /etc/autostart
 					}
 					sleep 1
 					screen -wipe >/dev/null
 				}
-				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
+				echo -e "\033[1;32mDESATIVANDO O SOCKS OPEN\033[1;33m"
 				echo ""
-				fun_bar 'fun_wssocksoff'
+				fun_bar 'fun_socksopenoff'
 				echo ""
-				echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
+				echo -e "\033[1;32mSOCKS DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 2
+				fun_socks
+			else
+				clear
+				echo -e "\E[41;1;37m            SOCKS OPENVPN  + ANTCRASH           \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 2
+					clear
+					fun_conexao
+				}
+				verif_ptrs $porta
+				fun_inisocksop() {
+					screen -dmS proxy2 antcrashvpn3.sh "$porta"
+					[[ $(grep -wc "antcrashvpn3.sh" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn3.sh $porta" >>/etc/autostart
+					} || {
+						sed -i '/antcrashvpn3.sh/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn3.sh $porta" >>/etc/autostart
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O SOCKS OPENVPN + ANTCRASH\033[1;33m"
+				echo ""
+				fun_bar 'fun_inisocksop'
+				echo ""
+				echo -e "\033[1;32mSOCKS OPENVPN + ANTCRASH ATIVADO COM SUCESSO\033[1;33m"
+				sleep 3
+				fun_socks
+			fi
+			elif [[ "$resposta" = '3' ]]; then
+			if ps x | grep -w antcrashvpn4.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m             PROXY WEBSOCKET             \E[0m"
+				echo ""
+				fun_socksoff() {
+					for pidproxy in $(screen -ls | grep ".proxy3" | awk {'print $1'}); do
+						screen -X -S "$pidproxy" kill
+					done
+					[[ $(grep -wc "antcrashvpn4.sh" /etc/autostart) != '0' ]] && {
+						sed -i '/antcrashvpn4.sh/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O PROXY WEBSOCKET \033[1;33m"
+				echo ""
+				fun_bar 'fun_socksoff'
+				echo ""
+				echo -e "\033[1;32mPROXY WEBSOCKET  DESATIVADO COM SUCESSO!\033[1;33m"
 				sleep 3
 				fun_socks
 			else
 				clear
-				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
+				echo -e "\E[44;1;37m             PROXY WEBSOCKET            \E[0m"
 				echo ""
 				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
 				read porta
@@ -1594,44 +1645,30 @@ exit 0' >$RCLOCAL
 					fun_conexao
 				}
 				verif_ptrs $porta
-				fun_iniwssocks() {
+				fun_inisocks() {
 					sleep 1
-					screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta
-					[[ $(grep -wc "wsproxy.py" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
+					screen -dmS proxy3 antcrashvpn4.sh "$porta"
+					[[ $(grep -wc "antcrashvpn4.sh" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy3 antcrashvpn4.sh $porta" >>/etc/autostart
 					} || {
-						sed -i '/wsproxy.py/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
+						sed -i '/antcrashvpn4.sh/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy3 antcrashvpn4.sh $porta" >>/etc/autostart
 					}
 				}
 				echo ""
-				echo -e "\033[1;32mINICIANDO O WEBSOCKET\033[1;33m"
+				echo -e "\033[1;32mINICIANDO O PROXY WEBSOCKET \033[1;33m"
 				echo ""
-				fun_bar 'fun_iniwssocks'
+				fun_bar 'fun_inisocks'
 				echo ""
-				echo -e "\033[1;32WSSOCKS ATIVADO COM SUCESSO\033[1;33m"
+				echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
-			fi
+			    fi
 
-
-
-
-
-
-
-
-
-
-
-
-
-
-elif [[ "$resposta" = '3' ]]; then
-		clear
-		if ps x | grep -w WebSocket | grep -v grep 1>/dev/null 2>/dev/null; then
-		figlet '' | lolcat
-		echo -e "\E[41;1;37m            WEBSOCKET SECURITY             \E[0m"
+        elif [[ "$resposta" = '4' ]]; then
+			if ps x | grep -w antcrashvpn5.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m            WEBSOCKET SECURITY             \E[0m"
 				echo ""
 				fun_socksoff() {
 					for pidproxy in $(screen -ls | grep ".proxy4" | awk {'print $1'}); do
@@ -1660,9 +1697,6 @@ elif [[ "$resposta" = '3' ]]; then
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
-					sleep 3
-					clear
-					fun_conexao
 					sleep 3
 					clear
 					fun_conexao
