Add files via upload

diff --git a/F2/Modulos/conexao b/F2/Modulos/conexao
--- a/F2/Modulos/conexao
+++ b/F2/Modulos/conexao
@@ -654,26 +654,26 @@ SCOLOR='\033[0m'
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
-			echo -e "\E[44;1;37m              GERENCIAR SSL TUNNEL               \E[0m"
-			echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sslt"
-			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA SSL TUNNEL\033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER SSL TUNNEL\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
-			echo ""
-			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+			echo -e "\033[0;34m┃\E[44;1;37m           GERENCIAR SSL TUNNEL          \E[0m\033[0;34m┃"
+			echo -e "\033[0;34m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
+			echo -e "\033[0;34m╼ \033[1;32mPORTAS\033[1;37m: \033[1;37m$sslt"
+			echo -e "\033[0;34m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
+			echo -e "\033[0;34m┃\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA SSL TUNNEL\033[0m           \033[0;34m┃"
+			echo -e "\033[0;34m┃\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER SSL TUNNEL\033[0m                 \033[0;34m┃"
+			echo -e "\033[0;34m┃\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m                             \033[0;34m┃"
+			echo -e "\033[0;34m╰┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
+			echo -ne "\033[0;34m ╰╼\033[1;32mOQUE DESEJA FAZER \033[1;37m?\033[1;31m?\033[1;37m: "
 			read resposta
 			echo ""
 			[[ "$resposta" = '1' ]] && {
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;37m?\033[1;37m "
 				read porta
 				echo ""
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
-					sleep 2
 					clear
-					fun_conexao
+					inst_ssl
 				}
 				verif_ptrs $porta
 				echo -e "\033[1;32mALTERANDO PORTA SSL TUNNEL!"
@@ -686,98 +686,106 @@ SCOLOR='\033[0m'
 				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
 				echo ""
 				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mPORTA ALTERADA COM SUCESSO !" || echo -e "\033[1;31mERRO INESPERADO!"
-				sleep 3.5s
 				clear
-				fun_conexao
+				inst_ssl
 			}
 			[[ "$resposta" = '2' ]] && {
 				echo -e "\033[1;32mREMOVENDO O  SSL TUNNEL !\033[0m"
 				del_ssl() {
+					pkill stunnel4
 					service stunnel4 stop
 					apt-get remove stunnel4 -y
 					apt-get autoremove stunnel4 -y
 					apt-get purge stunnel4 -y
 					rm -rf /etc/stunnel/stunnel.conf
 					rm -rf /etc/default/stunnel4
-					rm -rf /etc/stunnel/cert.cert
-					rm -rf /etc/stunnel/key.key
+					rm -rf /etc/stunnel/stunnel.pem
 				}
 				echo ""
 				fun_bar 'del_ssl'
 				echo ""
 				echo -e "\033[1;32mSSL TUNNEL REMOVIDO COM SUCESSO!\033[0m"
-				sleep 3
+				inst_ssl
+			} || {
+				echo -e "\033[1;31mRetornando...\033[0m"
 				fun_conexao
 			}
 		else
 			clear
-			echo -e "\E[44;1;37m              INSTALAR SSL TUNNEL               \E[0m"
-			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL PADRÃO\033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL WEBSOCKET\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
-			echo ""
-			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
-			read resposta
-			echo ""
-			if [[ "$resposta" = '1' ]]; then
-				portssl='22'
-			elif [[ "$resposta" = '2' ]]; then
-				portssl='80'
-			elif [[ "$resposta" = '0' ]]; then
-				echo -e "\033[1;31mRetornando...\033[0m"
-				sleep 3
-				fun_conexao
-			else
-				echo ""
-				echo -e "\033[1;31mOpcao invalida !\033[0m"
-				sleep 1
-				inst_ssl
-			fi
 			clear
-			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
-			echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
-			echo ""
-			echo -ne "\033[1;32mDESEJA CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+			echo -e "\033[0;34m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
+			echo -e "\033[0;34m┃\E[44;1;37m           INSTALAR SSL TUNNEL           \E[0m\033[0;34m┃"
+			echo -e "\033[0;34m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
+		echo -e "\033[0;34m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
+		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL PADRÃO\033[0m         \033[0;34m┃"
+		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL WEBSOCKET\033[0m      \033[0;34m┃"
+		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m                             \033[0;34m┃" 
+		echo -e "\033[0;34m╰┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
+		echo -ne "\033[0;34m ╰╼\033[1;32mOQUE DESEJA FAZER \033[1;37m?\033[1;31m?\033[1;37m: "
 			read resposta
-			[[ "$resposta" = 's' ]] && {
-				echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O SSL TUNNEL !\033[0m"
+			echo ""
+            if [[ "$resposta" = '1' ]]; then
+                portssl='22'
+            elif [[ "$resposta" = '2' ]]; then     
+                portssl='80'
+            elif [[ "$resposta" = '0' ]]; then
+				echo -e "\033[1;31mRetornando...\033[0m"
+				sleep 1
+				fun_conexao
+            else
+			echo ""
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			inst_ssl
+		fi
+            clear
+			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
+			echo -e "\n\033[1;37mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
+			{
 				echo ""
 				read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 443 porta
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
-					sleep 3
 					clear
-					fun_conexao
-				}
+					inst_ssl
+					}
 				verif_ptrs $porta
-				echo -e "\n\033[1;32mINSTALANDO O SSL TUNNEL !\033[1;33m"
-				echo ""
-				fun_bar 'apt-get update -y' 'apt-get install stunnel4 -y'
+				apt-get install stunnel4 -y
+				echo -e "client = no\n[SSL]\ncert = /etc/stunnel/stunnel.pem\naccept = 443 \nconnect = 127.0.0.1:80" > /etc/stunnel/stunnel.conf
+				openssl genrsa -out stunnel.key 2048 > /dev/null 2>&1
+				(echo "" ; echo "" ; echo "" ; echo "" ; echo "" ; echo "" ; echo "@cloudflare" )|openssl req -new -key stunnel.key -x509 -days 1000 -out stunnel.crt 
+				cat stunnel.crt stunnel.key > stunnel.pem 
+				mv stunnel.pem /etc/stunnel/
+				sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
+				service stunnel4 restart 
+				rm -rf /etc/ger-frm/stunnel.crt 
+				rm -rf /etc/ger-frm/stunnel.key
+				rm -rf /root/stunnel.crt
+				rm -rf /root/stunnel.key
 				echo -e "\n\033[1;32mCONFIGURANDO O SSL TUNNEL !\033[0m"
 				echo ""
 				ssl_conf() {
-					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${portssl}\naccept = ${porta}" >/etc/stunnel/stunnel.conf
+					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:$portssl\naccept = ${porta}" >/etc/stunnel/stunnel.conf
 				}
 				fun_bar 'ssl_conf'
 				echo -e "\n\033[1;32mCRIANDO CERTIFICADO !\033[0m"
 				echo ""
 				ssl_certif() {
-					crt='EC'
-					openssl genrsa -out key.pem 2048 >/dev/null 2>&1
-					(
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-						echo $crt
-					) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
-					cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
-					rm key.pem cert.pem >/dev/null 2>&1
+					#crt='EC'
+					#openssl genrsa -out key.pem 2048 >/dev/null 2>&1
+					#(
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
+					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
+					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/Niltonjuniorxd/SSHPLUSnzx/nzxs/Install/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
 				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
@@ -788,28 +796,10 @@ SCOLOR='\033[0m'
 					/etc/init.d/stunnel4 restart
 				}
 				fun_bar 'fun_finssl' 'service stunnel4 restart'
-				echo -e "\n\033[1;32mSSL TUNNEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m$porta\033[0m"
+				echo -e "\n\033[1;32mSSL TUNNEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;37m$porta\033[0m"
 				sleep 1
 				clear
-				echo -e "Corrigindo SSL CLARO"
-				cd /etc/stunnel/
-				rm -rf stunnel.conf
-				rm -rf stunnel.pem
-				wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/Install/cert
-				wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/Install/key
-				wget https://raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/Install/stunnel
-				mv cert cert.pem
-				mv key key.pem
-				mv stunnel stunnel.conf
-				chmod 777 cert.pem
-				chmod 777 key.pem
-				chmod 777 stunnel.conf
-				service stunnel4 restart
-				cd $HOME
-				clear
-				echo -e "Corrigido"
-				sleep 2
-				fun_conexao
+				inst_ssl
 			} || {
 				echo -e "\n\033[1;31mRetornando...\033[0m"
 				sleep 2
