Add files via upload

diff --git a/F2/Modulos/conexao b/F2/Modulos/conexao
--- a/F2/Modulos/conexao
+++ b/F2/Modulos/conexao
@@ -19,7 +19,7 @@ SCOLOR='\033[0m'
 		comando[1]="$2"
 		(
 			[[ -e $HOME/fim ]] && rm $HOME/fim
-			[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
+			[[ ! -d /etc/CrashVPN ]] && rm -rf /bin/menu
 			${comando[0]} >/dev/null 2>&1
 			${comando[1]} >/dev/null 2>&1
 			touch $HOME/fim
@@ -55,18 +55,6 @@ SCOLOR='\033[0m'
 		done
 	}
 
-	slow_setup() {
-		[[ -e "/bin/slowdns" ]] && {
-			slowdns
-		} || {
-			cd $HOME
-			wget https://raw.githubusercontent.com/kiritosshxd/SSHPLUS/main/Slowdns/install -o /dev/null
-			chmod 777 install
-			./install
-		}
-
-	}
-
 	inst_sqd() {
 		if netstat -nltp | grep 'squid' 1>/dev/null 2>/dev/null; then
 			echo -e "\E[41;1;37m            REMOVER SQUID PROXY              \E[0m"
@@ -86,7 +74,6 @@ SCOLOR='\033[0m'
 						apt-get remove squid3 -y >/dev/null 2>&1
 						apt-get purge squid3 -y >/dev/null 2>&1
 						rm -rf /etc/squid3 >/dev/null 2>&1
-						apt autoremove -y >/dev/null 2>&1
 					}
 				}
 				fun_bar 'rem_sqd'
@@ -100,6 +87,98 @@ SCOLOR='\033[0m'
 				clear
 				fun_conexao
 			}
+		else
+			clear
+			echo -e "\E[44;1;37m              INSTALADOR SQUID                \E[0m"
+			echo ""
+			IP=$(wget -qO- ipv4.icanhazip.com)
+			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
+			read -e -i $IP ipdovps
+			[[ -z "$ipdovps" ]] && {
+				echo -e "\n\033[1;31mIP invalido\033[1;32m"
+				echo ""
+				read -p "Digite seu IP: " IP
+			}
+			echo -e "\n\033[1;33mQUAIS PORTAS DESEJA ULTILIZAR NO SQUID \033[1;31m?"
+			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDEFINA AS PORTAS EM SEQUENCIA \033[1;33mEX: \033[1;37m80 8080 8799"
+			echo ""
+			echo -ne "\033[1;32mINFORME AS PORTAS\033[1;37m: "
+			read portass
+			[[ -z "$portass" ]] && {
+				echo -e "\n\033[1;31mPorta invalida!"
+				sleep 3
+				fun_conexao
+			}
+			for porta in $(echo -e $portass); do
+				verif_ptrs $porta
+			done
+			echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m"
+			echo ""
+			fun_bar 'apt-get update -y' 'apt-get install squid3 -y'
+			sleep 1
+			[[ -d "/etc/squid/" ]] && {
+				var_sqd="/etc/squid/squid.conf"
+				var_pay="/etc/squid/payload.txt"
+			} || {
+				[[ -d "/etc/squid3/" ]] && {
+					var_sqd="/etc/squid3/squid.conf"
+					var_pay="/etc/squid3/payload.txt"
+				}
+			}
+			echo ".claro.com.br/
+.claro.com.sv/
+.facebook.net/
+.netclaro.com.br/
+.speedtest.net/
+.tim.com.br/
+.vivo.com.br/
+.oi.com.br/" >$var_pay
+			echo "acl url1 dstdomain -i 127.0.0.1
+acl url2 dstdomain -i localhost
+acl url3 dstdomain -i $ipdovps
+acl url4 dstdomain -i /CrashVPN?
+acl payload url_regex -i "$var_pay"
+acl all src 0.0.0.0/0
+
+http_access allow url1
+http_access allow url2
+http_access allow url3
+http_access allow url4
+http_access allow payload
+http_access deny all
+ 
+#Portas" >$var_sqd
+			for Pts in $(echo -e $portass); do
+				echo -e "http_port $Pts" >>$var_sqd
+				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
+			done
+			echo -e "
+#Nome squid
+visible_hostname NONE 
+via off
+forwarded_for off
+pipeline_prefetch off" >>$var_sqd
+			sqd_conf() {
+				[[ -d "/etc/squid/" ]] && {
+					squid -k reconfigure
+					service ssh restart
+					service squid restart
+				} || {
+					[[ -d "/etc/squid3/" ]] && {
+						squid3 -k reconfigure
+						service ssh restart
+						service squid3 restart
+					}
+				}
+			}
+			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
+			echo ""
+			fun_bar 'sqd_conf'
+			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
+			sleep 3.5s
+			fun_conexao
+		fi
+	}
 		else
 			clear
 			echo -e "\E[44;1;37m              INSTALADOR SQUID                \E[0m"
